
package vista;

/**
 *
 * @author Matias Dieguez
 */
public class VentanaAdministrador extends javax.swing.JFrame
{

    /** Creates new form VentanaPrincipal */
    public VentanaAdministrador()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        panelPrincipal = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        panelCentralIzquierdo = new javax.swing.JPanel();
        panelInferiorCenIzq = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaListaColaboradores = new javax.swing.JTextArea();
        panelSuperiorCenIzq = new javax.swing.JPanel();
        labelListaDeColaboradores = new javax.swing.JLabel();
        panelInferiorIzquierdo = new javax.swing.JPanel();
        panelIzquierdoInfIzq = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaListaServicios = new javax.swing.JTextArea();
        panelSuperiorIzq = new javax.swing.JPanel();
        labelListaDeServicios = new javax.swing.JLabel();
        panelCentralDerecho = new javax.swing.JPanel();
        panelInferiorCenDer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaListaClientes = new javax.swing.JTextArea();
        panelSuperiorCenDer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        checkBoxServicio = new javax.swing.JCheckBox();
        checkBoxCliente = new javax.swing.JCheckBox();
        checkBoxColaborador = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        botonCrear = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        panelDerecho = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaInformes = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.GridLayout());

        panelIzquierdo.setLayout(new java.awt.GridLayout(2, 1));

        panelCentralIzquierdo.setLayout(new java.awt.BorderLayout());

        panelInferiorCenIzq.setLayout(new java.awt.BorderLayout());

        textAreaListaColaboradores.setColumns(20);
        textAreaListaColaboradores.setRows(5);
        jScrollPane3.setViewportView(textAreaListaColaboradores);

        panelInferiorCenIzq.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        panelCentralIzquierdo.add(panelInferiorCenIzq, java.awt.BorderLayout.CENTER);

        panelSuperiorCenIzq.setLayout(new java.awt.BorderLayout());

        labelListaDeColaboradores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelListaDeColaboradores.setText("LISTA COLABORADORES");
        panelSuperiorCenIzq.add(labelListaDeColaboradores, java.awt.BorderLayout.CENTER);

        panelCentralIzquierdo.add(panelSuperiorCenIzq, java.awt.BorderLayout.PAGE_START);

        panelIzquierdo.add(panelCentralIzquierdo);

        panelInferiorIzquierdo.setLayout(new java.awt.BorderLayout());

        panelIzquierdoInfIzq.setLayout(new java.awt.BorderLayout());

        textAreaListaServicios.setColumns(20);
        textAreaListaServicios.setRows(5);
        jScrollPane4.setViewportView(textAreaListaServicios);

        panelIzquierdoInfIzq.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        panelInferiorIzquierdo.add(panelIzquierdoInfIzq, java.awt.BorderLayout.CENTER);

        panelSuperiorIzq.setLayout(new java.awt.BorderLayout());

        labelListaDeServicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelListaDeServicios.setText("LISTA SERVICIOS");
        panelSuperiorIzq.add(labelListaDeServicios, java.awt.BorderLayout.CENTER);

        panelInferiorIzquierdo.add(panelSuperiorIzq, java.awt.BorderLayout.PAGE_START);

        panelIzquierdo.add(panelInferiorIzquierdo);

        panelPrincipal.add(panelIzquierdo);

        panelCentralDerecho.setLayout(new java.awt.BorderLayout());

        panelInferiorCenDer.setLayout(new java.awt.BorderLayout());

        textAreaListaClientes.setColumns(20);
        textAreaListaClientes.setRows(5);
        jScrollPane1.setViewportView(textAreaListaClientes);

        panelInferiorCenDer.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelCentralDerecho.add(panelInferiorCenDer, java.awt.BorderLayout.CENTER);

        panelSuperiorCenDer.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LISTA CLIENTES");
        panelSuperiorCenDer.add(jLabel3, java.awt.BorderLayout.CENTER);

        panelCentralDerecho.add(panelSuperiorCenDer, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        checkBoxServicio.setText("Servicio");
        checkBoxServicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(checkBoxServicio);

        checkBoxCliente.setText("Cliente");
        checkBoxCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(checkBoxCliente);

        checkBoxColaborador.setText("Colaborador");
        checkBoxColaborador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(checkBoxColaborador);

        jPanel1.add(jPanel4);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        botonCrear.setText("CREAR");
        botonCrear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonCrearActionPerformed(evt);
            }
        });
        jPanel2.add(botonCrear);

        botonEliminar.setText("ELIMINAR");
        botonEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(botonEliminar);

        jPanel1.add(jPanel2);

        panelCentralDerecho.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        panelPrincipal.add(panelCentralDerecho);

        panelDerecho.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMES");
        jPanel5.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        textAreaInformes.setColumns(20);
        textAreaInformes.setRows(5);
        jScrollPane2.setViewportView(textAreaInformes);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelDerecho.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        jButton3.setText("Generar informe Clientes");
        jPanel6.add(jButton3);

        jButton2.setText("Generar informe Tareas activas");
        jPanel6.add(jButton2);

        jButton1.setText("Generar informe Colaboradores");
        jPanel6.add(jButton1);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        panelDerecho.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        panelPrincipal.add(panelDerecho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCrearActionPerformed
    {//GEN-HEADEREND:event_botonCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonEliminarActionPerformed
    {//GEN-HEADEREND:event_botonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAdministrador.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAdministrador.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAdministrador.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAdministrador.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    new VentanaAdministrador().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JCheckBox checkBoxCliente;
    private javax.swing.JCheckBox checkBoxColaborador;
    private javax.swing.JCheckBox checkBoxServicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelListaDeColaboradores;
    private javax.swing.JLabel labelListaDeServicios;
    private javax.swing.JPanel panelCentralDerecho;
    private javax.swing.JPanel panelCentralIzquierdo;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelInferiorCenDer;
    private javax.swing.JPanel panelInferiorCenIzq;
    private javax.swing.JPanel panelInferiorIzquierdo;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelIzquierdoInfIzq;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperiorCenDer;
    private javax.swing.JPanel panelSuperiorCenIzq;
    private javax.swing.JPanel panelSuperiorIzq;
    private javax.swing.JTextArea textAreaInformes;
    private javax.swing.JTextArea textAreaListaClientes;
    private javax.swing.JTextArea textAreaListaColaboradores;
    private javax.swing.JTextArea textAreaListaServicios;
    // End of variables declaration//GEN-END:variables

}
