
package vista;

import controlador.Controlador;

import java.awt.event.ActionListener;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.util.Iterator;

import javax.swing.DefaultListModel;

/**
 *
 * @author Matias Dieguez
 */
public class VentanaAdministrador extends javax.swing.JFrame
{
    public static final String CREAR="CREAR";
    public static final String ELIMINAR="ELIMINAR";
    public static final String InfoCliente="InfoCliente";
    public static final String InfoTareasAct="InfoTareasAct";
    public static final String InfoColaboradores="InfoColaboradores";
    public static final int CheckCliente=1;
    public static final int CheckCServicio=2;
    public static final int CheckColaborador=3;
    private DefaultListModel modeloListaCliente = new DefaultListModel();
    private DefaultListModel modeloListaColaboradores = new DefaultListModel();
    private DefaultListModel modeloListaServicios = new DefaultListModel();
    

    /** Creates new form VentanaPrincipal */
    public VentanaAdministrador()
    {
        initComponents();
        this.setVisible(true);
        this.botonCrearColaborador.setActionCommand(VentanaAdministrador.CREAR);
        this.botonCrearServicio.setActionCommand(VentanaAdministrador.ELIMINAR);
        this.botonInfoClientes.setActionCommand(VentanaAdministrador.InfoCliente);
        this.botonInfoColaboradores.setActionCommand(VentanaAdministrador.InfoColaboradores);
        this.botonInfoTareas.setActionCommand(VentanaAdministrador.InfoTareasAct);
        this.listaClientes.setModel(this.modeloListaCliente);
        this.listaColaboradores.setModel(this.modeloListaColaboradores);
        this.listaServicios.setModel(this.modeloListaServicios);
        this.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent evt)
            {
                Controlador.terminar();
                
            }
        });
    }
    
    public void addActionListener(ActionListener al)
    {
        this.botonCrearColaborador.addActionListener(al);
        this.botonCrearServicio.addActionListener(al);
        this.botonInfoClientes.addActionListener(al);
        this.botonInfoColaboradores.addActionListener(al);
        this.botonInfoTareas.addActionListener(al);
        
    }

    public void actualizarListaCliente(Iterator clientes)
    {
        while (clientes.hasNext())
            this.modeloListaCliente.addElement(clientes.next());
    }
    public void actualizarListaServicios(Iterator servicios){
        while (servicios.hasNext())
            this.modeloListaServicios.addElement(servicios.next());
    }
    public void actualizarListaColaboradores(Iterator colaboradores){
        while (colaboradores.hasNext())
            this.modeloListaColaboradores.addElement(colaboradores.next());
    }
    public int checkActivo()
    {//hacer
        return 0;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        panelPrincipal = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        panelCentralIzquierdo = new javax.swing.JPanel();
        panelInferiorCenIzq = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaColaboradores = new javax.swing.JList<>();
        panelSuperiorCenIzq = new javax.swing.JPanel();
        labelListaDeColaboradores = new javax.swing.JLabel();
        panelInferiorIzquierdo = new javax.swing.JPanel();
        panelIzquierdoInfIzq = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaServicios = new javax.swing.JList<>();
        panelSuperiorIzq = new javax.swing.JPanel();
        labelListaDeServicios = new javax.swing.JLabel();
        panelCentralDerecho = new javax.swing.JPanel();
        panelInferiorCenDer = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList<>();
        panelSuperiorCenDer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonCrearColaborador = new javax.swing.JButton();
        botonCrearCliente = new javax.swing.JButton();
        botonCrearServicio = new javax.swing.JButton();
        botonEliminarColaborador = new javax.swing.JButton();
        botonEliminarCliente = new javax.swing.JButton();
        botonEliminarServicio = new javax.swing.JButton();
        panelDerecho = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaInformes = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        botonInfoClientes = new javax.swing.JButton();
        botonInfoTareas = new javax.swing.JButton();
        botonInfoColaboradores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.GridLayout(1, 0));

        panelIzquierdo.setLayout(new java.awt.GridLayout(2, 1));

        panelCentralIzquierdo.setLayout(new java.awt.BorderLayout());

        panelInferiorCenIzq.setLayout(new java.awt.BorderLayout());

        listaColaboradores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaColaboradores);

        panelInferiorCenIzq.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        panelCentralIzquierdo.add(panelInferiorCenIzq, java.awt.BorderLayout.CENTER);

        panelSuperiorCenIzq.setLayout(new java.awt.BorderLayout());

        labelListaDeColaboradores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelListaDeColaboradores.setText("LISTA COLABORADORES");
        panelSuperiorCenIzq.add(labelListaDeColaboradores, java.awt.BorderLayout.CENTER);

        panelCentralIzquierdo.add(panelSuperiorCenIzq, java.awt.BorderLayout.PAGE_START);

        panelIzquierdo.add(panelCentralIzquierdo);

        panelInferiorIzquierdo.setLayout(new java.awt.BorderLayout());

        panelIzquierdoInfIzq.setLayout(new java.awt.BorderLayout());

        listaServicios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaServicios);

        panelIzquierdoInfIzq.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelInferiorIzquierdo.add(panelIzquierdoInfIzq, java.awt.BorderLayout.CENTER);

        panelSuperiorIzq.setLayout(new java.awt.BorderLayout());

        labelListaDeServicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelListaDeServicios.setText("LISTA SERVICIOS");
        panelSuperiorIzq.add(labelListaDeServicios, java.awt.BorderLayout.CENTER);

        panelInferiorIzquierdo.add(panelSuperiorIzq, java.awt.BorderLayout.PAGE_START);

        panelIzquierdo.add(panelInferiorIzquierdo);

        panelPrincipal.add(panelIzquierdo);

        panelCentralDerecho.setLayout(new java.awt.BorderLayout());

        panelInferiorCenDer.setLayout(new java.awt.BorderLayout());

        listaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listaClientes);

        panelInferiorCenDer.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        panelCentralDerecho.add(panelInferiorCenDer, java.awt.BorderLayout.CENTER);

        panelSuperiorCenDer.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LISTA CLIENTES");
        panelSuperiorCenDer.add(jLabel3, java.awt.BorderLayout.CENTER);

        panelCentralDerecho.add(panelSuperiorCenDer, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        botonCrearColaborador.setText("Crear Colaborador");
        botonCrearColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearColaboradorActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearColaborador);

        botonCrearCliente.setText("Crear Cliente");
        jPanel1.add(botonCrearCliente);

        botonCrearServicio.setText("Crear Servicio");
        botonCrearServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearServicioActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearServicio);

        botonEliminarColaborador.setText("Eliminar Colaborador");
        jPanel1.add(botonEliminarColaborador);

        botonEliminarCliente.setText("Eliminar Cliente");
        jPanel1.add(botonEliminarCliente);

        botonEliminarServicio.setText("Eliminar Servicio");
        jPanel1.add(botonEliminarServicio);

        panelCentralDerecho.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        panelPrincipal.add(panelCentralDerecho);

        panelDerecho.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMES");
        jPanel5.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        textAreaInformes.setColumns(20);
        textAreaInformes.setRows(5);
        jScrollPane2.setViewportView(textAreaInformes);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelDerecho.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        botonInfoClientes.setText("Generar informe Clientes");
        jPanel6.add(botonInfoClientes);

        botonInfoTareas.setText("Generar informe Tareas activas");
        jPanel6.add(botonInfoTareas);

        botonInfoColaboradores.setText("Generar informe Colaboradores");
        jPanel6.add(botonInfoColaboradores);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        panelDerecho.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        panelPrincipal.add(panelDerecho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void botonCrearColaboradorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCrearColaboradorActionPerformed
    {//GEN-HEADEREND:event_botonCrearColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCrearColaboradorActionPerformed

    private void botonCrearServicioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonCrearServicioActionPerformed
    {//GEN-HEADEREND:event_botonCrearServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCrearServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAdministrador.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAdministrador.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAdministrador.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAdministrador.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    new VentanaAdministrador().setVisible(true);
                }
            });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCliente;
    private javax.swing.JButton botonCrearColaborador;
    private javax.swing.JButton botonCrearServicio;
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JButton botonEliminarColaborador;
    private javax.swing.JButton botonEliminarServicio;
    private javax.swing.JButton botonInfoClientes;
    private javax.swing.JButton botonInfoColaboradores;
    private javax.swing.JButton botonInfoTareas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelListaDeColaboradores;
    private javax.swing.JLabel labelListaDeServicios;
    private javax.swing.JList<String> listaClientes;
    private javax.swing.JList<String> listaColaboradores;
    private javax.swing.JList<String> listaServicios;
    private javax.swing.JPanel panelCentralDerecho;
    private javax.swing.JPanel panelCentralIzquierdo;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelInferiorCenDer;
    private javax.swing.JPanel panelInferiorCenIzq;
    private javax.swing.JPanel panelInferiorIzquierdo;
    private javax.swing.JPanel panelIzquierdo;
    private javax.swing.JPanel panelIzquierdoInfIzq;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperiorCenDer;
    private javax.swing.JPanel panelSuperiorCenIzq;
    private javax.swing.JPanel panelSuperiorIzq;
    private javax.swing.JTextArea textAreaInformes;
    // End of variables declaration//GEN-END:variables

}
